# Enable or disable debug mode for verbose internal logging (useful during development and bug report)
debug: true

tnt:
  knockback:
    # Horizontal force applied to entities by TNT explosion
    horizontal: 1.0
    # Vertical lift given to entities by TNT explosion
    vertical: 0.8

  explosion:
    # Explosion strength (affects blast radius and block damage)
    power: 4.0
    # Deprecated: whether the explosion breaks blocks (no longer recommended)
    break-blocks: false

  damage:
    # Amount of damage inflicted to the TNT owner when it explodes
    self: 4.0
    # Amount of damage inflicted to other entities caught in the blast
    others: 8.0

  fuse-time:
    # Time in game ticks before TNT explodes after being ignited (20 ticks = 1 second)
    ticks: 40

fireball:
  knockback:
    # Horizontal force applied to entities by fired fireballs
    horizontal: 1.5
    # Vertical lift given to entities by fired fireballs
    vertical: 0.8
    # Configurable knockback radius
    radius: 5.0

  explosion:
    # Explosion strength when a fireball impacts (usually smaller than TNT)
    power: 1.0
    # Deprecated: whether the explosion breaks blocks (no longer recommended)
    break-blocks: false
    # Whether the explosion should set blocks on fire around the impact
    make-fire: true

  damage:
    # Damage to shooter if their own fireball hits something
    self: 2.0
    # Damage to other entities hit by the fireball explosion
    others: 4.0

  # Multiplier applied to default fireball speed (use higher value for faster projectiles)
  speed-multiplier: 4.0
  # Cooldown time in seconds between consecutive fireball launches
  cooldown: 0.1
  # Whether players can hit (melee‐attack) a launched fireball
  hit-enabled: true

egg-bridge:
  # Time in seconds that the egg continues building
  duration: 2

  bridge:
    # How many blocks at most will be generated per egg (0 to unlimited)
    max-length: 512
    # Width (number of blocks per cross-section)
    width: 3
    # Height relative to the egg (e.g. -1 = one block lower)
    height-offset: -3

  projectile:
    # Egg speed multiplier
    speed-multiplier: 1.0
    # If the egg is affected by gravity
    gravity-enabled: true
    # Cooldown in seconds between casts
    cooldown: 1.0

  particles:
    enabled: true
    # Particle type (e.g. REDSTONE, SMOKE)
    type: STEP_SOUND
    data: 4
    # Interval in ticks between particle emissions
    interval-ticks: 5

# If players feel hungry
player-hungry: false

database:
  # MySQL (Hikari), SQLite
  type: SQLite
  mysql:
    host: "localhost"
    port: 3306
    database: "bedwars2030"
    username: "root"
    password: ""
